import random
import math
def guessTheNumber(y):
    random_number = random.randint(1, y)
    guess = 0
    while guess != random_number:
        guess = (int(input(f"Make a guess between 1 and {y} ")))
        if guess < random_number:
            print("too low")
        elif guess > random_number:
            print("too high")
    print(f"Congrats! You guess the random number {random_number} generated by computer.  ")
    
# guessTheNumber(100)

def guessTheNumberComp(x):
    a = int(input("Please enter lower bound: "))
    b = int(input("Please enter upper bound: "))
    comp_guess = round((a+b)/2)
    while comp_guess != x:
        
        if x < comp_guess :
            print(comp_guess)
            b = round((a+b)/2)
            comp_guess = math.floor((a+b)/2)
        elif x > comp_guess:
            print(comp_guess)
            a = round((a+b)/2)
            comp_guess = math.ceil((a+b)/2)
            
        
    print(f"The number you choose is {comp_guess} and computer find it correctly. ")
    
# guessTheNumberComp(50)
